// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Url from "../src/client/Url.js";
import * as Parser from "../src/client/Parser.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Navigation from "../src/client/Navigation.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function assertEq(name, actual, expected) {
  if (Primitive_object.equal(actual, expected)) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name);
    console.error(`  Expected: ` + Belt_Option.getWithDefault(JSON.stringify(expected), "?"));
    console.error(`  Actual:   ` + Belt_Option.getWithDefault(JSON.stringify(actual), "?"));
  }
}

function windowExists() {
  try {
    return (typeof window !== 'undefined');
  } catch (exn) {
    return false;
  }
}

function skipIfNoBrowser(name, test) {
  if (windowExists()) {
    return test();
  } else {
    console.log(`[SKIP] ` + name + ` (skipped - no browser environment)`);
    return;
  }
}

function toString(route) {
  if (typeof route !== "object") {
    if (route === "Home") {
      return "/";
    } else {
      return "/profile";
    }
  } else {
    return "/user/" + String(route._0);
  }
}

function fromUrl(url) {
  let parser = Parser.oneOf([
    Parser.map(Parser.top, () => "Home"),
    Parser.map(Parser.s("profile"), () => "Profile"),
    Parser.map(Parser.andThen(Parser.s("user"), Parser.int), param => ({
      TAG: "User",
      _0: param[1]
    }))
  ]);
  return Parser.parse(parser, url);
}

let TestRoute = {
  toString: toString,
  fromUrl: fromUrl
};

let Nav = Navigation.Make(TestRoute);

function testFunctorTypes() {
  console.log("[PASS] Navigation.Make functor types compile correctly");
}

function testUrlConstruction() {
  assertEq("toString: Home", "/", "/");
  assertEq("toString: Profile", "/profile", "/profile");
  assertEq("toString: User(42)", toString({
    TAG: "User",
    _0: 42
  }), "/user/42");
}

function testRoundtrip() {
  let routes = [
    "Home",
    "Profile",
    {
      TAG: "User",
      _0: 123
    }
  ];
  Belt_Array.forEach(routes, route => {
    let url = toString(route);
    let parsed = fromUrl(Url.fromString(url));
    let name = `roundtrip: ` + url;
    if (parsed !== undefined) {
      if (Primitive_object.equal(parsed, route)) {
        console.log(`[PASS] ` + name);
      } else {
        console.error(`[FAIL] ` + name + ` - parsed to different route`);
      }
    } else {
      console.error(`[FAIL] ` + name + ` - failed to parse`);
    }
  });
}

function testPushUrl() {
  skipIfNoBrowser("pushUrl changes location", () => {
    Navigation.currentUrl();
    Navigation.pushUrl("/test-push");
    let after = Navigation.currentUrl();
    if (Url.pathToString(after) === "/test-push") {
      console.log("[PASS] pushUrl changes location");
      return Navigation.back();
    } else {
      console.error("[FAIL] pushUrl did not change location");
      return;
    }
  });
}

function testReplaceUrl() {
  skipIfNoBrowser("replaceUrl changes location without history", () => {
    Navigation.replaceUrl("/test-replace");
    let current = Navigation.currentUrl();
    if (Url.pathToString(current) === "/test-replace") {
      console.log("[PASS] replaceUrl changes location");
    } else {
      console.error("[FAIL] replaceUrl did not change location");
    }
  });
}

function testOnUrlChange() {
  skipIfNoBrowser("onUrlChange subscription", () => {
    let received = {
      contents: false
    };
    let unsubscribe = Navigation.onUrlChange(param => {
      received.contents = true;
    });
    console.log("[PASS] onUrlChange returns unsubscribe function");
    unsubscribe();
  });
}

function testTypedNavigation() {
  skipIfNoBrowser("typed navigation with Make functor", () => {
    Nav.pushRoute("Profile");
    let current = Navigation.currentUrl();
    if (Url.pathToString(current) === "/profile") {
      console.log("[PASS] Nav.pushRoute works with typed routes");
      return Navigation.back();
    } else {
      console.error("[FAIL] Nav.pushRoute did not navigate correctly");
      return;
    }
  });
}

function runAll() {
  console.log("=== Navigation Module Tests ===");
  console.log("\n-- Functor Types --");
  testFunctorTypes();
  console.log("\n-- URL Construction --");
  testUrlConstruction();
  console.log("\n-- Roundtrip --");
  testRoundtrip();
  console.log("\n-- Browser-Dependent (may skip) --");
  testPushUrl();
  testReplaceUrl();
  testOnUrlChange();
  testTypedNavigation();
  console.log("\n=== Navigation Tests Complete ===");
}

runAll();

export {
  assertEq,
  windowExists,
  skipIfNoBrowser,
  TestRoute,
  Nav,
  testFunctorTypes,
  testUrlConstruction,
  testRoundtrip,
  testPushUrl,
  testReplaceUrl,
  testOnUrlChange,
  testTypedNavigation,
  runAll,
}
/* Nav Not a pure module */
