// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Url from "../src/client/Url.js";
import * as Parser from "../src/client/Parser.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as NestedRoute from "../src/client/NestedRoute.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function assertEq(name, actual, expected) {
  if (Primitive_object.equal(actual, expected)) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name);
    console.error(`  Expected: ` + Belt_Option.getWithDefault(JSON.stringify(expected), "?"));
    console.error(`  Actual:   ` + Belt_Option.getWithDefault(JSON.stringify(actual), "?"));
  }
}

function assertSome(name, actual) {
  if (actual !== undefined) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name + ` - expected Some, got None`);
  }
}

function assertNone(name, actual) {
  if (actual !== undefined) {
    console.error(`[FAIL] ` + name + ` - expected None, got Some`);
  } else {
    console.log(`[PASS] ` + name);
  }
}

function routeEq(a, b) {
  return a === b;
}

function testLeaf() {
  let tree = NestedRoute.leaf("Dashboard");
  if (tree.TAG === "Leaf") {
    return assertEq("leaf: creates leaf node", tree._0, "Dashboard");
  }
  console.error("[FAIL] leaf: should create Leaf variant");
}

function testBranch() {
  let tree = NestedRoute.branch("Dashboard", [
    NestedRoute.leaf("DashboardOverview"),
    NestedRoute.leaf("DashboardAnalytics")
  ]);
  if (tree.TAG === "Leaf") {
    console.error("[FAIL] branch: should create Branch variant");
    return;
  }
  assertEq("branch: parent route", tree.route, "Dashboard");
  assertEq("branch: child count", tree.children.length, 2);
}

function testIndex() {
  let tree = NestedRoute.index("Settings", "SettingsProfile", [NestedRoute.leaf("SettingsSecurity")]);
  if (tree.TAG === "Leaf") {
    console.error("[FAIL] index: should create Branch variant");
    return;
  }
  assertEq("index: parent route", tree.route, "Settings");
  assertEq("index: child count", tree.children.length, 2);
}

function testFindLeafInTree() {
  let tree = NestedRoute.branch("Root", [
    NestedRoute.branch("Dashboard", [NestedRoute.leaf("DashboardOverview")]),
    NestedRoute.leaf("Settings")
  ]);
  let result = NestedRoute.findInTree(tree, "DashboardOverview", routeEq, /* [] */0);
  assertSome("findInTree: finds nested leaf", result);
  if (result !== undefined) {
    assertEq("findInTree: correct leaf", result.leaf, "DashboardOverview");
    return assertEq("findInTree: path depth", result.segments.length, 2);
  }
}

function testFindBranchInTree() {
  let tree = NestedRoute.branch("Root", [NestedRoute.branch("Dashboard", [NestedRoute.leaf("DashboardOverview")])]);
  let result = NestedRoute.findInTree(tree, "Dashboard", routeEq, /* [] */0);
  assertSome("findInTree: finds branch route", result);
}

function testFindNotInTree() {
  let tree = NestedRoute.branch("Root", [NestedRoute.leaf("Dashboard")]);
  let result = NestedRoute.findInTree(tree, "Settings", routeEq, /* [] */0);
  assertNone("findInTree: returns None for missing route", result);
}

function testGetLayoutContexts() {
  let tree = NestedRoute.branch("Root", [NestedRoute.branch("Dashboard", [
      NestedRoute.leaf("DashboardOverview"),
      NestedRoute.leaf("DashboardAnalytics")
    ])]);
  let def = NestedRoute.make(tree, param => "DashboardOverview", param => "/dashboard/overview", routeEq);
  let contexts = NestedRoute.getLayoutContexts(def, "DashboardOverview");
  assertEq("getLayoutContexts: context count", contexts.length, 3);
  let ctx = Belt_Array.get(contexts, 0);
  if (ctx !== undefined) {
    assertEq("getLayoutContexts: first route", ctx.route, "Root");
    assertEq("getLayoutContexts: first depth", ctx.depth, 0);
    assertEq("getLayoutContexts: first isLeaf", ctx.isLeaf, false);
  } else {
    console.error("[FAIL] getLayoutContexts: missing first context");
  }
  let ctx$1 = Belt_Array.get(contexts, 2);
  if (ctx$1 !== undefined) {
    assertEq("getLayoutContexts: last route", ctx$1.route, "DashboardOverview");
    return assertEq("getLayoutContexts: last isLeaf", ctx$1.isLeaf, true);
  } else {
    console.error("[FAIL] getLayoutContexts: missing last context");
    return;
  }
}

function testGetLayoutContextsNotFound() {
  let tree = NestedRoute.leaf("Root");
  let def = NestedRoute.make(tree, param => {}, param => {}, routeEq);
  let contexts = NestedRoute.getLayoutContexts(def, "NotFound");
  assertEq("getLayoutContexts not found: empty array", contexts.length, 0);
}

function testNestedParser() {
  let parentParser = Parser.s("dashboard");
  let childParser = Parser.s("overview");
  let combined = NestedRoute.nestedParser(parentParser, childParser, (param, param$1) => "DashboardOverview");
  let url = Url.fromString("/dashboard/overview");
  let result = Parser.parse(combined, url);
  assertEq("nestedParser: parses nested route", result, "DashboardOverview");
}

function testOptionalChildWithChild() {
  let parentParser = Parser.s("settings");
  let childParser = Parser.s("security");
  let combined = NestedRoute.optionalChild(parentParser, childParser, () => "Settings", (param, param$1) => "SettingsSecurity");
  let url = Url.fromString("/settings/security");
  let result = Parser.parse(combined, url);
  assertEq("optionalChild with child: parses full path", result, "SettingsSecurity");
}

function testOptionalChildWithoutChild() {
  let parentParser = Parser.s("settings");
  let childParser = Parser.s("security");
  let combined = NestedRoute.optionalChild(parentParser, childParser, () => "Settings", (param, param$1) => "SettingsSecurity");
  let url = Url.fromString("/settings");
  let result = Parser.parse(combined, url);
  assertEq("optionalChild without child: parses parent only", result, "Settings");
}

function runTests() {
  console.log("=== NestedRoute Tests ===");
  testLeaf();
  testBranch();
  testIndex();
  testFindLeafInTree();
  testFindBranchInTree();
  testFindNotInTree();
  testGetLayoutContexts();
  testGetLayoutContextsNotFound();
  testNestedParser();
  testOptionalChildWithChild();
  testOptionalChildWithoutChild();
  console.log("=== NestedRoute Tests Complete ===");
}

runTests();

export {
  assertEq,
  assertSome,
  assertNone,
  routeEq,
  testLeaf,
  testBranch,
  testIndex,
  testFindLeafInTree,
  testFindBranchInTree,
  testFindNotInTree,
  testGetLayoutContexts,
  testGetLayoutContextsNotFound,
  testNestedParser,
  testOptionalChildWithChild,
  testOptionalChildWithoutChild,
  runTests,
}
/*  Not a pure module */
