// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Url from "../src/client/Url.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as RouteBuilder from "../src/client/RouteBuilder.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function assertEq(name, actual, expected) {
  if (Primitive_object.equal(actual, expected)) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name);
    console.error(`  Expected: ` + Belt_Option.getWithDefault(JSON.stringify(expected), "?"));
    console.error(`  Actual:   ` + Belt_Option.getWithDefault(JSON.stringify(actual), "?"));
  }
}

function assertSome(name, actual) {
  if (actual !== undefined) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name + ` - expected Some, got None`);
  }
}

function assertNone(name, actual) {
  if (actual !== undefined) {
    console.error(`[FAIL] ` + name + ` - expected None, got Some`);
  } else {
    console.log(`[PASS] ` + name);
  }
}

function fromString(s) {
  if (s.length > 0) {
    return {
      TAG: "UserId",
      _0: s
    };
  }
}

function toString(s) {
  return s._0;
}

let UserId = {
  fromString: fromString,
  toString: toString
};

let homeRoute = RouteBuilder.build(RouteBuilder.end_, () => "Home", route => {
  if (typeof route !== "object" && route === "Home") {
    return Primitive_option.some(undefined);
  }
});

let profileRoute = RouteBuilder.build(RouteBuilder.andThen(RouteBuilder.lit("profile"), RouteBuilder.end_), param => "Profile", route => {
  if (typeof route !== "object" && route === "Profile") {
    return [
      undefined,
      undefined
    ];
  }
});

let userRoute = RouteBuilder.build(RouteBuilder.andThen(RouteBuilder.andThen(RouteBuilder.lit("user"), RouteBuilder.int()), RouteBuilder.end_), param => ({
  TAG: "User",
  _0: param[0][1]
}), route => {
  if (typeof route !== "object" || route.TAG !== "User") {
    return;
  } else {
    return [
      [
        undefined,
        route._0
      ],
      undefined
    ];
  }
});

let userProfileRoute = RouteBuilder.build(RouteBuilder.andThen(RouteBuilder.andThen(RouteBuilder.andThen(RouteBuilder.andThen(RouteBuilder.lit("user"), RouteBuilder.int()), RouteBuilder.lit("profile")), RouteBuilder.str()), RouteBuilder.end_), arg => {
  let match = arg[0];
  return {
    TAG: "UserProfile",
    _0: match[0][0][1],
    _1: match[1]
  };
}, route => {
  if (typeof route !== "object" || route.TAG !== "UserProfile") {
    return;
  } else {
    return [
      [
        [
          [
            undefined,
            route._0
          ],
          undefined
        ],
        route._1
      ],
      undefined
    ];
  }
});

let itemRoute = RouteBuilder.build(RouteBuilder.andThen(RouteBuilder.andThen(RouteBuilder.lit("item"), RouteBuilder.custom(fromString, toString)), RouteBuilder.end_), arg => ({
  TAG: "Item",
  _0: arg[0][1]
}), route => {
  if (typeof route !== "object" || route.TAG !== "Item") {
    return;
  } else {
    return [
      [
        undefined,
        route._0
      ],
      undefined
    ];
  }
});

let router = RouteBuilder.oneOf([
  homeRoute,
  profileRoute,
  userRoute,
  userProfileRoute,
  itemRoute
]);

function testLiteralSegment() {
  let route = RouteBuilder.build(RouteBuilder.andThen(RouteBuilder.lit("test"), RouteBuilder.end_), param => "Profile", route => {
    if (typeof route !== "object" && route === "Profile") {
      return [
        undefined,
        undefined
      ];
    }
  });
  assertSome("lit: parses /test", route.parse(Url.fromString("/test")));
  assertNone("lit: rejects /other", route.parse(Url.fromString("/other")));
  assertEq("lit: serializes", route.toString("Profile"), "/test");
}

function testIntSegment() {
  let route = RouteBuilder.build(RouteBuilder.andThen(RouteBuilder.andThen(RouteBuilder.lit("num"), RouteBuilder.int()), RouteBuilder.end_), arg => ({
    TAG: "User",
    _0: arg[0][1]
  }), route => {
    if (typeof route !== "object" || route.TAG !== "User") {
      return;
    } else {
      return [
        [
          undefined,
          route._0
        ],
        undefined
      ];
    }
  });
  let match = route.parse(Url.fromString("/num/42"));
  if (typeof match === "object" && match.TAG === "User") {
    assertEq("int: parses /num/42", match._0, 42);
  } else {
    console.error("[FAIL] int: failed to parse /num/42");
  }
  assertNone("int: rejects /num/abc", route.parse(Url.fromString("/num/abc")));
  assertEq("int: serializes", route.toString({
    TAG: "User",
    _0: 123
  }), "/num/123");
}

function testStrSegment() {
  let route = RouteBuilder.build(RouteBuilder.andThen(RouteBuilder.andThen(RouteBuilder.lit("name"), RouteBuilder.str()), RouteBuilder.end_), arg => ({
    TAG: "UserProfile",
    _0: 0,
    _1: arg[0][1]
  }), route => {
    if (typeof route !== "object" || route.TAG !== "UserProfile") {
      return;
    } else {
      return [
        [
          undefined,
          route._1
        ],
        undefined
      ];
    }
  });
  let match = route.parse(Url.fromString("/name/alice"));
  if (typeof match === "object" && match.TAG === "UserProfile") {
    assertEq("str: parses /name/alice", match._1, "alice");
  } else {
    console.error("[FAIL] str: failed to parse /name/alice");
  }
  assertEq("str: serializes", route.toString({
    TAG: "UserProfile",
    _0: 0,
    _1: "bob"
  }), "/name/bob");
}

function testCustomSegment() {
  assertSome("custom: parses /item/xyz", itemRoute.parse(Url.fromString("/item/xyz")));
  assertNone("custom: rejects /item/", itemRoute.parse(Url.fromString("/item/")));
  let s = itemRoute.toString({
    TAG: "Item",
    _0: {
      TAG: "UserId",
      _0: "abc"
    }
  });
  if (s !== undefined) {
    return assertEq("custom: serializes", s, "/item/abc");
  } else {
    console.error("[FAIL] custom: failed to serialize");
    return;
  }
}

function testRouterParsing() {
  assertEq("router: parses /", router.parse(Url.fromString("/")), "Home");
  assertEq("router: parses /profile", router.parse(Url.fromString("/profile")), "Profile");
  assertEq("router: parses /user/42", router.parse(Url.fromString("/user/42")), {
    TAG: "User",
    _0: 42
  });
  let match = router.parse(Url.fromString("/user/5/profile/settings"));
  if (typeof match === "object" && match.TAG === "UserProfile") {
    assertEq("router: user id", match._0, 5);
    assertEq("router: section", match._1, "settings");
  } else {
    console.error("[FAIL] router: failed to parse /user/5/profile/settings");
  }
  assertNone("router: rejects unknown", router.parse(Url.fromString("/unknown")));
}

function testRouterSerialization() {
  assertEq("router: serializes Home", router.toString("Home"), "/");
  assertEq("router: serializes Profile", router.toString("Profile"), "/profile");
  assertEq("router: serializes User(42)", router.toString({
    TAG: "User",
    _0: 42
  }), "/user/42");
  assertEq("router: serializes UserProfile", router.toString({
    TAG: "UserProfile",
    _0: 5,
    _1: "settings"
  }), "/user/5/profile/settings");
  assertEq("router: serializes Item", router.toString({
    TAG: "Item",
    _0: {
      TAG: "UserId",
      _0: "xyz"
    }
  }), "/item/xyz");
  assertNone("router: NotFound returns None", router.toString("NotFound"));
}

function testRoundtrip() {
  console.log("\n-- Roundtrip Tests (Bidirectional Guarantee) --");
  let routes = [
    "Home",
    "Profile",
    {
      TAG: "User",
      _0: 42
    },
    {
      TAG: "User",
      _0: 0
    },
    {
      TAG: "User",
      _0: -5
    },
    {
      TAG: "UserProfile",
      _0: 1,
      _1: "dashboard"
    },
    {
      TAG: "Item",
      _0: {
        TAG: "UserId",
        _0: "abc123"
      }
    }
  ];
  Belt_Array.forEach(routes, route => {
    let url = router.toString(route);
    if (url !== undefined) {
      let parsed = router.parse(Url.fromString(url));
      if (parsed !== undefined) {
        if (Primitive_object.equal(parsed, route)) {
          console.log(`[PASS] roundtrip: ` + url);
        } else {
          console.error(`[FAIL] roundtrip: ` + url + ` - parsed to different route`);
        }
      } else {
        console.error(`[FAIL] roundtrip: ` + url + ` - failed to parse`);
      }
      return;
    }
    console.error(`[FAIL] roundtrip: failed to serialize route`);
  });
}

let Router = RouteBuilder.Make({
  definition: router,
  notFound: "NotFound"
});

function testMakeFunctor() {
  console.log("\n-- Make Functor Tests --");
  assertEq("Make.parse: /", Router.parse(Url.fromString("/")), "Home");
  assertEq("Make.parse: /profile", Router.parse(Url.fromString("/profile")), "Profile");
  assertEq("Make.parse: /unknown returns notFound", Router.parse(Url.fromString("/unknown")), "NotFound");
  assertEq("Make.toString: Home", Router.toString("Home"), "/");
  assertEq("Make.toString: Profile", Router.toString("Profile"), "/profile");
  assertEq("Make.toString: NotFound returns /", Router.toString("NotFound"), "/");
  assertSome("Make.parseOption: /", Router.parseOption(Url.fromString("/")));
  assertNone("Make.parseOption: /unknown", Router.parseOption(Url.fromString("/unknown")));
}

function runAll() {
  console.log("=== RouteBuilder Module Tests ===");
  console.log("\n-- Basic Segments --");
  testLiteralSegment();
  testIntSegment();
  testStrSegment();
  testCustomSegment();
  console.log("\n-- Router Parsing --");
  testRouterParsing();
  console.log("\n-- Router Serialization --");
  testRouterSerialization();
  testRoundtrip();
  testMakeFunctor();
  console.log("\n=== RouteBuilder Tests Complete ===");
}

runAll();

export {
  assertEq,
  assertSome,
  assertNone,
  UserId,
  homeRoute,
  profileRoute,
  userRoute,
  userProfileRoute,
  itemRoute,
  router,
  testLiteralSegment,
  testIntSegment,
  testStrSegment,
  testCustomSegment,
  testRouterParsing,
  testRouterSerialization,
  testRoundtrip,
  Router,
  testMakeFunctor,
  runAll,
}
/* homeRoute Not a pure module */
