// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RouteMeta from "../src/client/RouteMeta.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function assertEq(name, actual, expected) {
  if (Primitive_object.equal(actual, expected)) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name);
    console.error(`  Expected: ` + Belt_Option.getWithDefault(JSON.stringify(expected), "?"));
    console.error(`  Actual:   ` + Belt_Option.getWithDefault(JSON.stringify(actual), "?"));
  }
}

function assertTrue(name, actual) {
  if (actual) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name + ` - expected true`);
  }
}

function assertFalse(name, actual) {
  if (actual) {
    console.error(`[FAIL] ` + name + ` - expected false`);
  } else {
    console.log(`[PASS] ` + name);
  }
}

function testEmptyMeta() {
  assertEq("empty: title is None", RouteMeta.empty.title, undefined);
  assertEq("empty: breadcrumb is None", RouteMeta.empty.breadcrumb, undefined);
  assertFalse("empty: requiresAuth is false", RouteMeta.empty.requiresAuth);
  assertEq("empty: roles is empty", RouteMeta.empty.roles, []);
}

function testWithTitle() {
  let meta = RouteMeta.withTitle(RouteMeta.empty, "My Page");
  assertEq("withTitle: sets title", meta.title, "My Page");
}

function testWithBreadcrumb() {
  let meta = RouteMeta.withBreadcrumb(RouteMeta.empty, "Home");
  assertEq("withBreadcrumb: sets breadcrumb", meta.breadcrumb, "Home");
}

function testWithAuth() {
  let meta = RouteMeta.withAuth(RouteMeta.empty);
  assertTrue("withAuth: sets requiresAuth", meta.requiresAuth);
}

function testWithRoles() {
  let meta = RouteMeta.withRoles(RouteMeta.empty, [
    "admin",
    "editor"
  ]);
  assertTrue("withRoles: sets requiresAuth", meta.requiresAuth);
  assertEq("withRoles: sets roles", meta.roles, [
    "admin",
    "editor"
  ]);
}

function testFluentBuilder() {
  let meta = RouteMeta.withRoles(RouteMeta.withBreadcrumb(RouteMeta.withTitle(RouteMeta.empty, "Admin Panel"), "Admin"), ["admin"]);
  assertEq("fluent: title", meta.title, "Admin Panel");
  assertEq("fluent: breadcrumb", meta.breadcrumb, "Admin");
  assertTrue("fluent: requiresAuth", meta.requiresAuth);
  assertEq("fluent: roles", meta.roles, ["admin"]);
}

function testMakeHelper() {
  let meta = RouteMeta.make("Test", "Test Crumb", true, ["user"], undefined, undefined);
  assertEq("make: title", meta.title, "Test");
  assertEq("make: breadcrumb", meta.breadcrumb, "Test Crumb");
  assertTrue("make: requiresAuth", meta.requiresAuth);
  assertEq("make: roles", meta.roles, ["user"]);
}

function testPublicHelper() {
  let meta = RouteMeta.public_("Public Page", undefined, undefined);
  assertEq("public_: title", meta.title, "Public Page");
  assertFalse("public_: requiresAuth", meta.requiresAuth);
}

function testAuthenticatedHelper() {
  let meta = RouteMeta.authenticated("Private", undefined, ["admin"], undefined);
  assertEq("authenticated: title", meta.title, "Private");
  assertTrue("authenticated: requiresAuth", meta.requiresAuth);
  assertEq("authenticated: roles", meta.roles, ["admin"]);
}

function testCheckAuthPublicRoute() {
  let routeWithMeta_meta = RouteMeta.public_("Home", undefined, undefined);
  let routeWithMeta = {
    route: "Home",
    meta: routeWithMeta_meta
  };
  let result = RouteMeta.checkAuth(routeWithMeta, false, []);
  switch (result.TAG) {
    case "Allowed" :
      return assertEq("checkAuth public: allowed", result._0, "Home");
    case "RequiresLogin" :
    case "InsufficientRoles" :
      console.error("[FAIL] checkAuth public: should be Allowed");
      return;
  }
}

function testCheckAuthRequiresLoginNotLoggedIn() {
  let routeWithMeta_meta = RouteMeta.authenticated("Dashboard", undefined, undefined, undefined);
  let routeWithMeta = {
    route: "Dashboard",
    meta: routeWithMeta_meta
  };
  let result = RouteMeta.checkAuth(routeWithMeta, false, []);
  switch (result.TAG) {
    case "RequiresLogin" :
      return assertEq("checkAuth not logged in: requires login", result._0, "Dashboard");
    case "Allowed" :
    case "InsufficientRoles" :
      console.error("[FAIL] checkAuth not logged in: should be RequiresLogin");
      return;
  }
}

function testCheckAuthRequiresLoginLoggedIn() {
  let routeWithMeta_meta = RouteMeta.authenticated("Profile", undefined, undefined, undefined);
  let routeWithMeta = {
    route: "Profile",
    meta: routeWithMeta_meta
  };
  let result = RouteMeta.checkAuth(routeWithMeta, true, []);
  switch (result.TAG) {
    case "Allowed" :
      return assertEq("checkAuth logged in: allowed", result._0, "Profile");
    case "RequiresLogin" :
    case "InsufficientRoles" :
      console.error("[FAIL] checkAuth logged in: should be Allowed");
      return;
  }
}

function testCheckAuthInsufficientRoles() {
  let routeWithMeta_meta = RouteMeta.authenticated("Admin", undefined, ["admin"], undefined);
  let routeWithMeta = {
    route: "AdminPanel",
    meta: routeWithMeta_meta
  };
  let result = RouteMeta.checkAuth(routeWithMeta, true, ["user"]);
  switch (result.TAG) {
    case "Allowed" :
    case "RequiresLogin" :
      console.error("[FAIL] checkAuth insufficient roles: should be InsufficientRoles");
      return;
    case "InsufficientRoles" :
      assertEq("checkAuth insufficient roles: route", result._0, "AdminPanel");
      return assertEq("checkAuth insufficient roles: required", result._1, ["admin"]);
  }
}

function testCheckAuthSufficientRoles() {
  let routeWithMeta_meta = RouteMeta.authenticated("Admin", undefined, [
    "admin",
    "superuser"
  ], undefined);
  let routeWithMeta = {
    route: "AdminPanel",
    meta: routeWithMeta_meta
  };
  let result = RouteMeta.checkAuth(routeWithMeta, true, ["admin"]);
  switch (result.TAG) {
    case "Allowed" :
      return assertEq("checkAuth sufficient roles: allowed", result._0, "AdminPanel");
    case "RequiresLogin" :
    case "InsufficientRoles" :
      console.error("[FAIL] checkAuth sufficient roles: should be Allowed");
      return;
  }
}

function runTests() {
  console.log("=== RouteMeta Tests ===");
  testEmptyMeta();
  testWithTitle();
  testWithBreadcrumb();
  testWithAuth();
  testWithRoles();
  testFluentBuilder();
  testMakeHelper();
  testPublicHelper();
  testAuthenticatedHelper();
  testCheckAuthPublicRoute();
  testCheckAuthRequiresLoginNotLoggedIn();
  testCheckAuthRequiresLoginLoggedIn();
  testCheckAuthInsufficientRoles();
  testCheckAuthSufficientRoles();
  console.log("=== RouteMeta Tests Complete ===");
}

runTests();

export {
  assertEq,
  assertTrue,
  assertFalse,
  testEmptyMeta,
  testWithTitle,
  testWithBreadcrumb,
  testWithAuth,
  testWithRoles,
  testFluentBuilder,
  testMakeHelper,
  testPublicHelper,
  testAuthenticatedHelper,
  testCheckAuthPublicRoute,
  testCheckAuthRequiresLoginNotLoggedIn,
  testCheckAuthRequiresLoginLoggedIn,
  testCheckAuthInsufficientRoles,
  testCheckAuthSufficientRoles,
  runTests,
}
/*  Not a pure module */
