// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Url from "../src/client/Url.js";
import * as Parser from "../src/client/Parser.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as ServerRouter from "../src/server/ServerRouter.js";
import * as Belt_MapString from "@rescript/runtime/lib/es6/Belt_MapString.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function assertEq(name, actual, expected) {
  if (Primitive_object.equal(actual, expected)) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name);
    console.error(`  Expected: ` + Belt_Option.getWithDefault(JSON.stringify(expected), "?"));
    console.error(`  Actual:   ` + Belt_Option.getWithDefault(JSON.stringify(actual), "?"));
  }
}

function assertSome(name, actual) {
  if (actual !== undefined) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name + ` - expected Some, got None`);
  }
}

function assertNone(name, actual) {
  if (actual !== undefined) {
    console.error(`[FAIL] ` + name + ` - expected None, got Some`);
  } else {
    console.log(`[PASS] ` + name);
  }
}

function testMethodFromString() {
  assertEq("methodFromString GET", ServerRouter.methodFromString("GET"), "GET");
  assertEq("methodFromString POST", ServerRouter.methodFromString("POST"), "POST");
  assertEq("methodFromString PUT", ServerRouter.methodFromString("PUT"), "PUT");
  assertEq("methodFromString PATCH", ServerRouter.methodFromString("PATCH"), "PATCH");
  assertEq("methodFromString DELETE", ServerRouter.methodFromString("DELETE"), "DELETE");
  assertEq("methodFromString HEAD", ServerRouter.methodFromString("HEAD"), "HEAD");
  assertEq("methodFromString OPTIONS", ServerRouter.methodFromString("OPTIONS"), "OPTIONS");
  assertNone("methodFromString invalid", ServerRouter.methodFromString("INVALID"));
}

function testMethodFromStringCaseInsensitive() {
  assertEq("methodFromString lowercase", ServerRouter.methodFromString("get"), "GET");
  assertEq("methodFromString mixed case", ServerRouter.methodFromString("Post"), "POST");
}

function testMethodToString() {
  assertEq("methodToString GET", ServerRouter.methodToString("GET"), "GET");
  assertEq("methodToString POST", ServerRouter.methodToString("POST"), "POST");
  assertEq("methodToString DELETE", ServerRouter.methodToString("DELETE"), "DELETE");
}

function testMakeContext() {
  let ctx = ServerRouter.makeContext("/api/users", "GET", undefined, undefined);
  assertEq("makeContext: method", ctx.method, "GET");
  assertEq("makeContext: path", ctx.path, "/api/users");
  assertEq("makeContext: url path", ctx.url.path, {
    hd: "api",
    tl: {
      hd: "users",
      tl: /* [] */0
    }
  });
}

function testMakeContextWithQuery() {
  let ctx = ServerRouter.makeContext("/search?q=hello&page=2", "GET", undefined, undefined);
  assertEq("makeContext query: path", ctx.path, "/search");
  assertSome("makeContext query: has query param", Url.getQueryParam(ctx.url, "q"));
}

function testMakeContextWithHeaders() {
  let headers = Belt_MapString.fromArray([[
      "Content-Type",
      "application/json"
    ]]);
  let ctx = ServerRouter.makeContext("/api/data", "POST", Primitive_option.some(headers), undefined);
  assertEq("makeContext headers: has header", Belt_MapString.get(ctx.headers, "Content-Type"), "application/json");
}

function testMakeServerRoute() {
  let usersRoute = ServerRouter.make(Parser.map(Parser.andThen(Parser.s("api"), Parser.s("users")), param => "GetUsers"), ["GET"], (param, param$1) => ({
    TAG: "Render",
    _0: "users list"
  }));
  let ctx = ServerRouter.makeContext("/api/users", "GET", undefined, undefined);
  let result = ServerRouter.matchRoute(usersRoute, ctx);
  if (typeof result !== "object") {
    console.error("[FAIL] matchRoute: should match and render");
    return;
  }
  if (result.TAG === "Matched") {
    let data = result._0;
    if (typeof data !== "object") {
      console.error("[FAIL] matchRoute: should match and render");
      return;
    }
    if (data.TAG === "Render") {
      return assertEq("matchRoute: renders data", data._0, "users list");
    }
    console.error("[FAIL] matchRoute: should match and render");
    return;
  } else {
    console.error("[FAIL] matchRoute: should match and render");
    return;
  }
}

function testMatchRouteWrongMethod() {
  let usersRoute = ServerRouter.make(Parser.map(Parser.andThen(Parser.s("api"), Parser.s("users")), param => "GetUsers"), ["GET"], (param, param$1) => ({
    TAG: "Render",
    _0: "users list"
  }));
  let ctx = ServerRouter.makeContext("/api/users", "POST", undefined, undefined);
  let result = ServerRouter.matchRoute(usersRoute, ctx);
  if (typeof result !== "object") {
    console.error("[FAIL] matchRoute wrong method: should return WrongMethod");
    return;
  }
  if (result.TAG !== "Matched") {
    return assertEq("matchRoute wrong method: allowed methods", result._0, ["GET"]);
  }
  console.error("[FAIL] matchRoute wrong method: should return WrongMethod");
}

function testMatchRouteNoMatch() {
  let usersRoute = ServerRouter.make(Parser.map(Parser.andThen(Parser.s("api"), Parser.s("users")), param => "GetUsers"), ["GET"], (param, param$1) => ({
    TAG: "Render",
    _0: "users list"
  }));
  let ctx = ServerRouter.makeContext("/api/posts", "GET", undefined, undefined);
  let result = ServerRouter.matchRoute(usersRoute, ctx);
  if (typeof result !== "object") {
    console.log("[PASS] matchRoute no match: returns NoMatch");
    return;
  }
  if (result.TAG === "Matched") {
    console.error("[FAIL] matchRoute no match: should return NoMatch");
    return;
  }
  console.error("[FAIL] matchRoute no match: should return NoMatch");
}

function testHandlerRedirect() {
  let loginRoute = ServerRouter.make(Parser.map(Parser.s("dashboard"), () => {}), ["GET"], (param, param$1) => ({
    TAG: "Redirect",
    _0: "/login"
  }));
  let ctx = ServerRouter.makeContext("/dashboard", "GET", undefined, undefined);
  let result = ServerRouter.matchRoute(loginRoute, ctx);
  if (typeof result !== "object") {
    console.error("[FAIL] handler redirect: should redirect");
    return;
  }
  if (result.TAG === "Matched") {
    let url = result._0;
    if (typeof url !== "object") {
      console.error("[FAIL] handler redirect: should redirect");
      return;
    }
    if (url.TAG === "Redirect") {
      return assertEq("handler redirect: url", url._0, "/login");
    }
    console.error("[FAIL] handler redirect: should redirect");
    return;
  } else {
    console.error("[FAIL] handler redirect: should redirect");
    return;
  }
}

function testHandlerNotFound() {
  let maybeRoute = ServerRouter.make(Parser.map(Parser.s("maybe"), () => {}), ["GET"], (param, param$1) => "NotFound");
  let ctx = ServerRouter.makeContext("/maybe", "GET", undefined, undefined);
  let result = ServerRouter.matchRoute(maybeRoute, ctx);
  if (typeof result !== "object") {
    console.error("[FAIL] handler not found: should return NotFound");
    return;
  }
  if (result.TAG === "Matched") {
    let tmp = result._0;
    if (typeof tmp !== "object") {
      console.log("[PASS] handler not found: returns NotFound");
      return;
    }
    console.error("[FAIL] handler not found: should return NotFound");
    return;
  } else {
    console.error("[FAIL] handler not found: should return NotFound");
    return;
  }
}

function testHandlerServerError() {
  let errorRoute = ServerRouter.make(Parser.map(Parser.s("error"), () => {}), ["GET"], (param, param$1) => ({
    TAG: "ServerError",
    _0: "Something went wrong"
  }));
  let ctx = ServerRouter.makeContext("/error", "GET", undefined, undefined);
  let result = ServerRouter.matchRoute(errorRoute, ctx);
  if (typeof result !== "object") {
    console.error("[FAIL] handler error: should return ServerError");
    return;
  }
  if (result.TAG === "Matched") {
    let msg = result._0;
    if (typeof msg !== "object") {
      console.error("[FAIL] handler error: should return ServerError");
      return;
    }
    if (msg.TAG === "ServerError") {
      return assertEq("handler error: message", msg._0, "Something went wrong");
    }
    console.error("[FAIL] handler error: should return ServerError");
    return;
  } else {
    console.error("[FAIL] handler error: should return ServerError");
    return;
  }
}

function testExtractParams() {
  let url = Url.fromString("/api/users/123/posts");
  let params = ServerRouter.extractParams(url);
  assertEq("extractParams: extracts path segments", params, [
    "api",
    "users",
    "123",
    "posts"
  ]);
}

function testRedirectWithQuery() {
  let url = Url.fromString("/old-page?utm_source=google&ref=twitter");
  let newUrl = ServerRouter.redirectWithQuery("/new-page", url);
  assertEq("redirectWithQuery: preserves query", newUrl.includes("utm_source=google"), true);
}

function runTests() {
  console.log("=== ServerRouter Tests ===");
  testMethodFromString();
  testMethodFromStringCaseInsensitive();
  testMethodToString();
  testMakeContext();
  testMakeContextWithQuery();
  testMakeContextWithHeaders();
  testMakeServerRoute();
  testMatchRouteWrongMethod();
  testMatchRouteNoMatch();
  testHandlerRedirect();
  testHandlerNotFound();
  testHandlerServerError();
  testExtractParams();
  testRedirectWithQuery();
  console.log("=== ServerRouter Tests Complete ===");
}

runTests();

export {
  assertEq,
  assertSome,
  assertNone,
  testMethodFromString,
  testMethodFromStringCaseInsensitive,
  testMethodToString,
  testMakeContext,
  testMakeContextWithQuery,
  testMakeContextWithHeaders,
  testMakeServerRoute,
  testMatchRouteWrongMethod,
  testMatchRouteNoMatch,
  testHandlerRedirect,
  testHandlerNotFound,
  testHandlerServerError,
  testExtractParams,
  testRedirectWithQuery,
  runTests,
}
/*  Not a pure module */
