// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Url from "../src/client/Url.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Belt_MapString from "@rescript/runtime/lib/es6/Belt_MapString.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function assertEq(name, actual, expected) {
  if (Primitive_object.equal(actual, expected)) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name);
    console.error(`  Expected: ` + Belt_Option.getWithDefault(JSON.stringify(expected), "?"));
    console.error(`  Actual:   ` + Belt_Option.getWithDefault(JSON.stringify(actual), "?"));
  }
}

function assertTrue(name, condition) {
  if (condition) {
    console.log(`[PASS] ` + name);
  } else {
    console.error(`[FAIL] ` + name);
  }
}

function testFromStringSimplePath() {
  let url = Url.fromString("/profile");
  assertEq("fromString: simple path", url.path, {
    hd: "profile",
    tl: /* [] */0
  });
  assertEq("fromString: simple path - no query", Belt_MapString.isEmpty(url.query), true);
  assertEq("fromString: simple path - no fragment", url.fragment, undefined);
}

function testFromStringRoot() {
  let url = Url.fromString("/");
  assertEq("fromString: root path is empty list", url.path, /* [] */0);
}

function testFromStringNestedPath() {
  let url = Url.fromString("/journey/abc123/map");
  assertEq("fromString: nested path", url.path, {
    hd: "journey",
    tl: {
      hd: "abc123",
      tl: {
        hd: "map",
        tl: /* [] */0
      }
    }
  });
}

function testFromStringWithQuery() {
  let url = Url.fromString("/search?q=hello&page=2");
  assertEq("fromString: path with query", url.path, {
    hd: "search",
    tl: /* [] */0
  });
  assertEq("fromString: query param q", Belt_MapString.get(url.query, "q"), "hello");
  assertEq("fromString: query param page", Belt_MapString.get(url.query, "page"), "2");
}

function testFromStringWithFragment() {
  let url = Url.fromString("/docs#section-1");
  assertEq("fromString: path with fragment", url.path, {
    hd: "docs",
    tl: /* [] */0
  });
  assertEq("fromString: fragment", url.fragment, "section-1");
}

function testFromStringWithQueryAndFragment() {
  let url = Url.fromString("/page?tab=settings#advanced");
  assertEq("fromString: full URL - path", url.path, {
    hd: "page",
    tl: /* [] */0
  });
  assertEq("fromString: full URL - query", Belt_MapString.get(url.query, "tab"), "settings");
  assertEq("fromString: full URL - fragment", url.fragment, "advanced");
}

function testFromStringEncodedQuery() {
  let url = Url.fromString("/search?q=hello%20world");
  assertEq("fromString: URL-decoded query", Belt_MapString.get(url.query, "q"), "hello world");
}

function testFromStringEmptyQueryValue() {
  let url = Url.fromString("/page?flag");
  assertEq("fromString: empty query value", Belt_MapString.get(url.query, "flag"), "");
}

function testToStringSimple() {
  let url_path = {
    hd: "profile",
    tl: /* [] */0
  };
  let url = {
    path: url_path,
    query: undefined,
    fragment: undefined
  };
  assertEq("toString: simple path", Url.toString(url), "/profile");
}

function testToStringRoot() {
  let url = {
    path: /* [] */0,
    query: undefined,
    fragment: undefined
  };
  assertEq("toString: root", Url.toString(url), "/");
}

function testToStringWithQuery() {
  let url_path = {
    hd: "search",
    tl: /* [] */0
  };
  let url_query = Belt_MapString.fromArray([
    [
      "q",
      "hello"
    ],
    [
      "page",
      "2"
    ]
  ]);
  let url = {
    path: url_path,
    query: url_query,
    fragment: undefined
  };
  let result = Url.toString(url);
  assertTrue("toString: has path", result.startsWith("/search?"));
  assertTrue("toString: has q param", result.includes("q=hello"));
  assertTrue("toString: has page param", result.includes("page=2"));
}

function testToStringWithFragment() {
  let url_path = {
    hd: "docs",
    tl: /* [] */0
  };
  let url_fragment = "section";
  let url = {
    path: url_path,
    query: undefined,
    fragment: url_fragment
  };
  assertEq("toString: with fragment", Url.toString(url), "/docs#section");
}

function testToStringEncodesSpecialChars() {
  let url_path = {
    hd: "search",
    tl: /* [] */0
  };
  let url_query = Belt_MapString.fromArray([[
      "q",
      "hello world"
    ]]);
  let url = {
    path: url_path,
    query: url_query,
    fragment: undefined
  };
  let result = Url.toString(url);
  assertTrue("toString: encodes spaces", result.includes("hello%20world"));
}

function testPathToString() {
  let url_path = {
    hd: "journey",
    tl: {
      hd: "abc",
      tl: {
        hd: "map",
        tl: /* [] */0
      }
    }
  };
  let url_query = Belt_MapString.fromArray([[
      "tab",
      "settings"
    ]]);
  let url_fragment = "top";
  let url = {
    path: url_path,
    query: url_query,
    fragment: url_fragment
  };
  assertEq("pathToString: excludes query and fragment", Url.pathToString(url), "/journey/abc/map");
}

function testGetQueryParam() {
  let url = Url.fromString("/page?name=value&other=123");
  assertEq("getQueryParam: existing", Url.getQueryParam(url, "name"), "value");
  assertEq("getQueryParam: missing", Url.getQueryParam(url, "missing"), undefined);
}

function testGetQueryParamInt() {
  let url = Url.fromString("/page?count=42&name=text");
  assertEq("getQueryParamInt: valid int", Url.getQueryParamInt(url, "count"), 42);
  assertEq("getQueryParamInt: not an int", Url.getQueryParamInt(url, "name"), undefined);
  assertEq("getQueryParamInt: missing", Url.getQueryParamInt(url, "missing"), undefined);
}

function testGetQueryParamBool() {
  let url = Url.fromString("/page?enabled=true&disabled=false&flag=1&off=0&other=maybe");
  assertEq("getQueryParamBool: true", Url.getQueryParamBool(url, "enabled"), true);
  assertEq("getQueryParamBool: false", Url.getQueryParamBool(url, "disabled"), false);
  assertEq("getQueryParamBool: 1", Url.getQueryParamBool(url, "flag"), true);
  assertEq("getQueryParamBool: 0", Url.getQueryParamBool(url, "off"), false);
  assertEq("getQueryParamBool: other", Url.getQueryParamBool(url, "other"), false);
}

function testIsRoot() {
  let root = Url.fromString("/");
  let notRoot = Url.fromString("/page");
  assertTrue("isRoot: true for /", Url.isRoot(root));
  assertTrue("isRoot: false for /page", !Url.isRoot(notRoot));
}

function testRoundtrip() {
  let url = Url.fromString("/journey/abc123?tab=map&page=1#section");
  let result = Url.toString(url);
  let reparsed = Url.fromString(result);
  assertEq("roundtrip: path preserved", reparsed.path, url.path);
  assertEq("roundtrip: fragment preserved", reparsed.fragment, url.fragment);
  assertEq("roundtrip: query q preserved", Belt_MapString.get(reparsed.query, "tab"), Belt_MapString.get(url.query, "tab"));
}

function runAll() {
  console.log("=== Url Module Tests ===");
  console.log("\n-- fromString --");
  testFromStringSimplePath();
  testFromStringRoot();
  testFromStringNestedPath();
  testFromStringWithQuery();
  testFromStringWithFragment();
  testFromStringWithQueryAndFragment();
  testFromStringEncodedQuery();
  testFromStringEmptyQueryValue();
  console.log("\n-- toString --");
  testToStringSimple();
  testToStringRoot();
  testToStringWithQuery();
  testToStringWithFragment();
  testToStringEncodesSpecialChars();
  console.log("\n-- pathToString --");
  testPathToString();
  console.log("\n-- Query helpers --");
  testGetQueryParam();
  testGetQueryParamInt();
  testGetQueryParamBool();
  console.log("\n-- isRoot --");
  testIsRoot();
  console.log("\n-- Roundtrip --");
  testRoundtrip();
  console.log("\n=== Url Tests Complete ===");
}

runAll();

export {
  assertEq,
  assertTrue,
  testFromStringSimplePath,
  testFromStringRoot,
  testFromStringNestedPath,
  testFromStringWithQuery,
  testFromStringWithFragment,
  testFromStringWithQueryAndFragment,
  testFromStringEncodedQuery,
  testFromStringEmptyQueryValue,
  testToStringSimple,
  testToStringRoot,
  testToStringWithQuery,
  testToStringWithFragment,
  testToStringEncodesSpecialChars,
  testPathToString,
  testGetQueryParam,
  testGetQueryParamInt,
  testGetQueryParamBool,
  testIsRoot,
  testRoundtrip,
  runAll,
}
/*  Not a pure module */
