// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Url from "../src/client/Url.js";
import * as Parser from "../src/client/Parser.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function fromString(str) {
  if (str.length > 0) {
    return {
      TAG: "UserId",
      _0: str
    };
  }
}

function toString(str) {
  return str._0;
}

let parser = Parser.custom(fromString);

let UserId = {
  fromString: fromString,
  toString: toString,
  parser: parser
};

let parser$1 = Parser.oneOf([
  Parser.map(Parser.top, () => "Home"),
  Parser.map(Parser.s("profile"), () => "Profile"),
  Parser.map(Parser.andThen(Parser.s("user"), Parser.int), param => ({
    TAG: "User",
    _0: param[1]
  })),
  Parser.map(Parser.andThen(Parser.s("article"), parser), param => ({
    TAG: "Article",
    _0: param[1]
  })),
  Parser.map(Parser.andThen(Parser.s("search"), Parser.queryRequired("q")), param => ({
    TAG: "Search",
    _0: param[1]
  }))
]);

function routeToString(route) {
  if (typeof route !== "object") {
    switch (route) {
      case "Home" :
        return "/";
      case "Profile" :
        return "/profile";
      case "NotFound" :
        return "/not-found";
    }
  } else {
    switch (route.TAG) {
      case "User" :
        return "/user/" + String(route._0);
      case "Article" :
        return "/article/" + route._0._0;
      case "Search" :
        return "/search?q=" + route._0;
    }
  }
}

function runDemo() {
  console.log("=== cadre-router Demo ===");
  console.log("");
  let testUrls = [
    "/",
    "/profile",
    "/user/42",
    "/user/123",
    "/article/my-first-post",
    "/search?q=hello",
    "/unknown"
  ];
  Belt_Array.forEach(testUrls, urlStr => {
    let url = Url.fromString(urlStr);
    let parsed = Parser.parse(parser$1, url);
    console.log("URL: " + urlStr);
    if (parsed !== undefined) {
      let routeName;
      if (typeof parsed !== "object") {
        switch (parsed) {
          case "Home" :
            routeName = "Home";
            break;
          case "Profile" :
            routeName = "Profile";
            break;
          case "NotFound" :
            routeName = "NotFound";
            break;
        }
      } else {
        switch (parsed.TAG) {
          case "User" :
            routeName = "User(" + String(parsed._0) + ")";
            break;
          case "Article" :
            routeName = "Article(" + parsed._0._0 + ")";
            break;
          case "Search" :
            routeName = "Search(" + parsed._0 + ")";
            break;
        }
      }
      console.log("  -> Parsed: " + routeName);
      let serialized = routeToString(parsed);
      console.log("  -> Serialized: " + serialized);
    } else {
      console.log("  -> No match (would be NotFound)");
    }
    console.log("");
  });
  console.log("=== Demo Complete ===");
}

runDemo();

export {
  UserId,
  parser$1 as parser,
  routeToString,
  runDemo,
}
/* parser Not a pure module */
