// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Url from "./Url.js";

function toHashUrl(path) {
  let normalizedPath = path.startsWith("/") ? path : "/" + path;
  return "#" + normalizedPath;
}

function pushUrl(url) {
  let hashUrl = toHashUrl(url);
  let fullUrl = window.location.origin + window.location.pathname + hashUrl;
  window.history.pushState(null, "", fullUrl);
}

function replaceUrl(url) {
  let hashUrl = toHashUrl(url);
  let fullUrl = window.location.origin + window.location.pathname + hashUrl;
  window.history.replaceState(null, "", fullUrl);
}

function back() {
  window.history.back();
}

function forward() {
  window.history.forward();
}

function currentUrl() {
  let tmp;
  if (window.location.hash.startsWith("#/")) {
    tmp = window.location.hash.slice(1);
  } else if (window.location.hash.startsWith("#")) {
    let rest = window.location.hash.slice(1);
    tmp = rest === "" ? "/" : "/" + rest;
  } else {
    tmp = "/";
  }
  return Url.fromString(tmp);
}

function onUrlChange(callback) {
  let handler = param => callback(currentUrl());
  window.addEventListener("hashchange", handler);
  window.addEventListener("popstate", handler);
  return () => {
    window.removeEventListener("hashchange", handler);
    window.removeEventListener("popstate", handler);
  };
}

function Make(R) {
  let pushRoute = route => pushUrl(R.toString(route));
  let replaceRoute = route => replaceUrl(R.toString(route));
  return {
    pushRoute: pushRoute,
    replaceRoute: replaceRoute
  };
}

export {
  pushUrl,
  replaceUrl,
  back,
  forward,
  currentUrl,
  onUrlChange,
  Make,
}
/* No side effect */
