// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Navigation from "./Navigation.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as JsxRuntime from "react/jsx-runtime";

function Link(props) {
  let target = props.target;
  let onClick = props.onClick;
  let href = props.href;
  let handleClick = event => {
    if (onClick !== undefined) {
      onClick(event);
    }
    let shouldNavigate = !event.defaultPrevented && event.button === 0 && !event.metaKey && !event.altKey && !event.ctrlKey && !event.shiftKey && (target === undefined || Primitive_object.equal(target, "_self"));
    if (shouldNavigate) {
      event.preventDefault();
      return Navigation.pushUrl(href);
    }
  };
  return JsxRuntime.jsx("a", {
    children: props.children,
    className: props.className,
    style: props.style,
    href: href,
    target: target,
    onClick: handleClick
  });
}

let make = Link;

function Make(funarg) {
  let Nav = Navigation.Make(funarg);
  let Link$Make = props => {
    let route = props.route;
    let href = funarg.toString(route);
    let handleClick = event => {
      let shouldNavigate = !event.defaultPrevented && event.button === 0 && !event.metaKey && !event.altKey && !event.ctrlKey && !event.shiftKey;
      if (shouldNavigate) {
        event.preventDefault();
        return Nav.pushRoute(route);
      }
    };
    return JsxRuntime.jsx("a", {
      children: props.children,
      className: props.className,
      style: props.style,
      href: href,
      onClick: handleClick
    });
  };
  return {
    make: Link$Make
  };
}

export {
  make,
  Make,
}
/* react/jsx-runtime Not a pure module */
