// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "@rescript/runtime/lib/es6/Belt_List.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let empty_roles = [];

let empty = {
  title: undefined,
  breadcrumb: undefined,
  requiresAuth: false,
  roles: empty_roles,
  custom: undefined
};

function withTitle(meta, title) {
  return {
    title: title,
    breadcrumb: meta.breadcrumb,
    requiresAuth: meta.requiresAuth,
    roles: meta.roles,
    custom: meta.custom
  };
}

function withBreadcrumb(meta, breadcrumb) {
  return {
    title: meta.title,
    breadcrumb: breadcrumb,
    requiresAuth: meta.requiresAuth,
    roles: meta.roles,
    custom: meta.custom
  };
}

function withAuth(meta) {
  return {
    title: meta.title,
    breadcrumb: meta.breadcrumb,
    requiresAuth: true,
    roles: meta.roles,
    custom: meta.custom
  };
}

function withRoles(meta, roles) {
  return {
    title: meta.title,
    breadcrumb: meta.breadcrumb,
    requiresAuth: true,
    roles: roles,
    custom: meta.custom
  };
}

function withCustom(meta, custom) {
  return {
    title: meta.title,
    breadcrumb: meta.breadcrumb,
    requiresAuth: meta.requiresAuth,
    roles: meta.roles,
    custom: Primitive_option.some(custom)
  };
}

function build(routeBuilder, getMeta) {
  return {
    parse: url => {
      let route = routeBuilder.parse(url);
      if (route === undefined) {
        return;
      }
      let route$1 = Primitive_option.valFromOption(route);
      return {
        route: route$1,
        meta: getMeta(route$1)
      };
    },
    toString: routeBuilder.toString,
    getMeta: getMeta
  };
}

function checkAuth(routeWithMeta, isLoggedIn, userRoles) {
  let meta = routeWithMeta.meta;
  let route = routeWithMeta.route;
  if (!meta.requiresAuth) {
    return {
      TAG: "Allowed",
      _0: route
    };
  }
  if (!isLoggedIn) {
    return {
      TAG: "RequiresLogin",
      _0: route
    };
  }
  if (meta.roles.length === 0) {
    return {
      TAG: "Allowed",
      _0: route
    };
  }
  let hasRole = Belt_Array.some(meta.roles, role => Belt_Array.some(userRoles, userRole => userRole === role));
  if (hasRole) {
    return {
      TAG: "Allowed",
      _0: route
    };
  } else {
    return {
      TAG: "InsufficientRoles",
      _0: route,
      _1: meta.roles
    };
  }
}

function MakeBreadcrumbs(Config) {
  let collectBreadcrumbs = (_route, _acc) => {
    while (true) {
      let acc = _acc;
      let route = _route;
      let meta = Config.definition.getMeta(route);
      let url = Config.definition.toString(route);
      let b = meta.breadcrumb;
      let label;
      if (b !== undefined) {
        label = b;
      } else {
        let t = meta.title;
        label = t !== undefined ? t : "/";
      }
      let item_route = Primitive_option.some(route);
      let item = {
        label: label,
        route: item_route,
        url: url
      };
      let newAcc = {
        hd: item,
        tl: acc
      };
      let parent = Config.getParent(route);
      if (parent === undefined) {
        return newAcc;
      }
      _acc = newAcc;
      _route = Primitive_option.valFromOption(parent);
      continue;
    };
  };
  let breadcrumbs = route => Belt_List.toArray(collectBreadcrumbs(route, /* [] */0));
  return {
    breadcrumbs: breadcrumbs
  };
}

function make(title, breadcrumb, requiresAuthOpt, rolesOpt, custom, param) {
  let requiresAuth = requiresAuthOpt !== undefined ? requiresAuthOpt : false;
  let roles = rolesOpt !== undefined ? rolesOpt : [];
  return {
    title: title,
    breadcrumb: breadcrumb,
    requiresAuth: requiresAuth,
    roles: roles,
    custom: custom
  };
}

function public_(title, breadcrumb, param) {
  return make(title, breadcrumb, false, undefined, undefined, undefined);
}

function authenticated(title, breadcrumb, rolesOpt, param) {
  let roles = rolesOpt !== undefined ? rolesOpt : [];
  return make(title, breadcrumb, true, roles, undefined, undefined);
}

export {
  empty,
  withTitle,
  withBreadcrumb,
  withAuth,
  withRoles,
  withCustom,
  build,
  checkAuth,
  MakeBreadcrumbs,
  make,
  public_,
  authenticated,
}
/* No side effect */
